// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDprSI_WSNGZ9EVmMAcmdWVISk45UXjW5E',
    appId: '1:793639697045:web:c236a87fede48885ee399c',
    messagingSenderId: '793639697045',
    projectId: 'notehub-34963',
    authDomain: 'notehub-34963.firebaseapp.com',
    storageBucket: 'notehub-34963.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXFX8j03sovDv_B4HIhrr8CdLVQD-6hr0',
    appId: '1:793639697045:android:cbad2490549f0373ee399c',
    messagingSenderId: '793639697045',
    projectId: 'notehub-34963',
    storageBucket: 'notehub-34963.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4_g2Mq4SQRV2yN1t64Uyp6annsv7EKiA',
    appId: '1:793639697045:ios:97aca5bdb9d2429cee399c',
    messagingSenderId: '793639697045',
    projectId: 'notehub-34963',
    storageBucket: 'notehub-34963.firebasestorage.app',
    iosBundleId: 'com.example.notehub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4_g2Mq4SQRV2yN1t64Uyp6annsv7EKiA',
    appId: '1:793639697045:ios:97aca5bdb9d2429cee399c',
    messagingSenderId: '793639697045',
    projectId: 'notehub-34963',
    storageBucket: 'notehub-34963.firebasestorage.app',
    iosBundleId: 'com.example.notehub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDprSI_WSNGZ9EVmMAcmdWVISk45UXjW5E',
    appId: '1:793639697045:web:6831cbec42c3dafaee399c',
    messagingSenderId: '793639697045',
    projectId: 'notehub-34963',
    authDomain: 'notehub-34963.firebaseapp.com',
    storageBucket: 'notehub-34963.firebasestorage.app',
  );
}
